version: "3.4"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432"
    environment:
      POSTGRES_USER: "slimbo-sa"
      POSTGRES_PASSWORD: "6285b275805a115bd326acddc"
      POSTGRES_DB: "slimbo-db"
      PGDATA: /tmp
    volumes:
      - ${WEBAPP_STORAGE_HOME}/pg_data:/var/lib/postgresql/data

  slimbo:
    image: blangr/slimbo:latest
    ports:
      - "80:80"
    environment:
      CONNECTIONSTRINGS__POSTGRES: Host=postgres;Database=slimbo-db;Username=slimbo-sa;Password=6285b275805a115bd326acddc
